### ISSUE TITLE
APIKey is incorrect or does not exist

### ISSUE THREAD

**Issue by amiga** [willblaschko/AlexaAndroid#103]
api_key.txt is in AlexaAndroid-master\app\src\main\assets but it still says this. In logcat I see the following (package is wrong?)

erifyPayload for packageName=com.willblaschko.android.alexavoicelibrary
07-02 23:09:30.414 16152-16152/? W/com.amazon.identity.auth.device.appid.APIKeyDecoder: Failed to decode: Decoding fails: package names don't match! - com.willblaschko.android.alexavoicelibrary != com.amazon.alexa.avs.companion
07-02 23:09:30.414 16152-16152/? W/com.amazon.identity.auth.device.appid.APIKeyDecoder: Unable to decode APIKey for pkg=com.willblaschko.android.alexavoicelibrary
07-02 23:09:30.414 16152-16152/? E/AuthorizationHandler: Unable to Use Amazon Authorization Manager. APIKey is incorrect or does not exist. Does assets/api_key.txt exist in the main application?
                                                         java.lang.IllegalArgumentException: Invalid API Key
                                                             at com.amazon.identity.auth.device.authorization.api.AmazonAuthorizationManager.<init>(AmazonAuthorizationManager.java:119)
                                                             at com.willblaschko.android.alexa.AuthorizationManager.<init>(AuthorizationManager.java:56)
                                                             at com.willblaschko.android.alexa.AlexaManager.<init>(AlexaManager.java:70)
                                                             at com.willblaschko.android.alexa.AlexaManager.getInstance(AlexaManager.java:106)
                                                             at com.willblaschko.android.alexavoicelibrary.BaseActivity.initAlexaAndroid(BaseActivity.java:101)
                                                             at com.willblaschko.android.alexavoicelibrary.BaseActivity.onCreate(BaseActivity.java:68)
                                                             at com.willblaschko.android.alexavoicelibrary.MainActivity.onCreate(MainActivity.java:30)
                                                             at android.app.Activity.performCreate(Activity.java:5990)
                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                             at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                             at android.os.Looper.loop(Looper.java:135)
                                                             at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
07-02 23:09:30.565 16152-16175/? D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true

**Comment by amiga** [comment]
Oh looks like the package name needs to be changed in amazon, since i previously set it up for their companion app, so not a bug :)

**Comment by amiga** [comment]
Actually after setting up the new package name etc I am still getting this error, its slightly different now with no problems from package name:

07-02 23:32:37.354 26922-26922/? I/com.amazon.identity.auth.device.utils.ThirdPartyResourceParser: Attempting to parse API Key from assets directory
07-02 23:32:37.355 26922-26922/? I/com.amazon.identity.auth.device.appid.APIKeyDecoder: Begin decoding API Key for packageName=com.willblaschko.android.alexavoicelibrary
07-02 23:32:37.359 26922-26922/? D/com.amazon.identity.auth.device.appid.APIKeyDecoder.PII: APIKey:<obscured>
07-02 23:32:37.359 26922-26922/? I/com.amazon.identity.auth.device.appid.APIKeyDecoder: verifyPayload for packageName=com.willblaschko.android.alexavoicelibrary
07-02 23:32:37.359 26922-26922/? D/com.amazon.identity.auth.device.appid.APIKeyDecoder.PII: Validating MD5 signature in API key:<obscured>
07-02 23:32:37.361 26922-26922/? I/com.amazon.identity.auth.device.utils.PackageSignatureUtil: num sigs = 1
07-02 23:32:37.362 26922-26922/? D/com.amazon.identity.auth.device.utils.PackageSignatureUtil.PII: Fingerprint checking:<obscured>
07-02 23:32:37.362 26922-26922/? I/com.amazon.identity.auth.device.appid.APIKeyDecoder: Number of signatures = 1
07-02 23:32:37.362 26922-26922/? D/com.amazon.identity.auth.device.appid.APIKeyDecoder.PII: Fingerprint checking:<obscured>
07-02 23:32:37.362 26922-26922/? W/com.amazon.identity.auth.device.appid.APIKeyDecoder: Failed to decode: Decoding failed: certificate fingerprint can't be verified! pkg=com.willblaschko.android.alexavoicelibrary
07-02 23:32:37.363 26922-26922/? W/com.amazon.identity.auth.device.appid.APIKeyDecoder: Unable to decode APIKey for pkg=com.willblaschko.android.alexavoicelibrary
07-02 23:32:37.363 26922-26922/? E/AuthorizationHandler: Unable to Use Amazon Authorization Manager. APIKey is incorrect or does not exist. Does assets/api_key.txt exist in the main application?
                                                         java.lang.IllegalArgumentException: Invalid API Key
                                                             at com.amazon.identity.auth.device.authorization.api.AmazonAuthorizationManager.<init>(AmazonAuthorizationManager.java:119)
                                                             at com.willblaschko.android.alexa.AuthorizationManager.<init>(AuthorizationManager.java:56)
                                                             at com.willblaschko.android.alexa.AlexaManager.<init>(AlexaManager.java:70)
                                                             at com.willblaschko.android.alexa.AlexaManager.getInstance(AlexaManager.java:106)
                                                             at com.willblaschko.android.alexavoicelibrary.BaseActivity.initAlexaAndroid(BaseActivity.java:101)
                                                             at com.willblaschko.android.alexavoicelibrary.BaseActivity.onCreate(BaseActivity.java:68)
                                                             at com.willblaschko.android.alexavoicelibrary.MainActivity.onCreate(MainActivity.java:30)
                                                             at android.app.Activity.performCreate(Activity.java:5990)
                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                             at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                             at android.os.Looper.loop(Looper.java:135)
                                                             at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
07-02 23:32:37.481 26922-26937/? W/art: Suspending all threads took: 11.950ms
07-02 23:32:37.483 26922-26937/? I/art: Background partial concurrent mark sweep GC freed 393(61KB) AllocSpace objects, 0(0B) LOS objects, 39% free, 1854KB/3MB, paused 13.323ms total 25.011ms
07-02 23:32:37.524 26922-26949/? D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
                                                   
                                                   [ 07-02 23:32:37.525 26922:26922 D/         ]
                                                   HostConnection::get() New Host Connection established 0xb438f0d0, tid 26922
07-02 23:32:37.525 26922-26922/? D/Atlas: Validating map...
07-02 23:32:37.530 26922-26922/? I/DownChannelService: Launched
07-02 23:32:37.534 26922-26922/? W/System.err: java.lang.IllegalStateException: User is not logged in and no refresh token found.
07-02 23:32:37.534 26922-26922/? W/System.err:     at com.willblaschko.android.alexa.TokenManager.getAccessToken(TokenManager.java:150)
07-02 23:32:37.534 26922-26922/? W/System.err:     at com.willblaschko.android.alexa.service.DownChannelService.openDownChannel(DownChannelService.java:74)
07-02 23:32:37.534 26922-26922/? W/System.err:     at com.willblaschko.android.alexa.service.DownChannelService.onCreate(DownChannelService.java:59)
07-02 23:32:37.534 26922-26922/? W/System.err:     at android.app.ActivityThread.handleCreateService(ActivityThread.java:2761)
07-02 23:32:37.534 26922-26922/? W/System.err:     at android.app.ActivityThread.access$1800(ActivityThread.java:151)
07-02 23:32:37.534 26922-26922/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1386)
07-02 23:32:37.534 26922-26922/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
07-02 23:32:37.534 26922-26922/? W/System.err:     at android.os.Looper.loop(Looper.java:135)
07-02 23:32:37.534 26922-26922/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5254)
07-02 23:32:37.534 26922-26922/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-02 23:32:37.534 26922-26922/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
07-02 23:32:37.534 26922-26922/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
07-02 23:32:37.534 26922-26922/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                               
                                               [ 07-02 23:32:37.550 26922:26949 D/         ]
                                               HostConnection::get() New Host Connection established 0xaec39430, tid 26949
07-02 23:32:37.552 26922-26949/? I/OpenGLRenderer: Initialized EGL, version 1.4
07-02 23:32:37.552 26922-26949/? W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
07-02 23:32:37.578 26922-26949/? D/OpenGLRenderer: Enabling debug mode 0
07-02 23:32:37.665 26922-26922/? W/art: Before Android 4.1, method int android.support.v7.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
07-02 23:32:37.962 26922-26949/? V/RenderScript: 0xaed41800 Launching thread(s), CPUs 4

**Comment by amiga** [comment]
I refactored to a new package name, set it all up in the back end, changed the api key, but am still getting this error unfortunately, what am I doing wrong?

07-03 00:08:09.589 27617-27617/com.willblaschko.android.norbyvoicelibrary D/com.amazon.identity.auth.map.device.utils.MAPLog.PII: Extracting verison incremental:<obscured>
07-03 00:08:09.589 27617-27617/com.willblaschko.android.norbyvoicelibrary D/com.amazon.identity.auth.map.device.utils.MAPLog.PII: Extracting flavor:<obscured>
07-03 00:08:09.589 27617-27617/com.willblaschko.android.norbyvoicelibrary D/com.amazon.identity.auth.device.authorization.api.AmazonAuthorizationManager.PII: AmazonAuthorizationManager:sdkVer=3.0.0 libVer=3.5.3:<obscured>
07-03 00:08:09.589 27617-27617/com.willblaschko.android.norbyvoicelibrary I/com.amazon.identity.auth.device.appid.AbstractAppIdentifier: getAppInfo : packageName=com.willblaschko.android.norbyvoicelibrary
07-03 00:08:09.589 27617-27617/com.willblaschko.android.norbyvoicelibrary I/com.amazon.identity.auth.device.appid.AbstractAppIdentifier: getAppInfoFromAPIKey : packageName=com.willblaschko.android.norbyvoicelibrary
07-03 00:08:09.589 27617-27617/com.willblaschko.android.norbyvoicelibrary I/com.amazon.identity.auth.device.appid.AbstractAppIdentifier: Finding API Key for com.willblaschko.android.norbyvoicelibrary
07-03 00:08:09.590 27617-27617/com.willblaschko.android.norbyvoicelibrary I/com.amazon.identity.auth.device.utils.ThirdPartyResourceParser: Attempting to parse API Key from assets directory
07-03 00:08:09.592 27617-27617/com.willblaschko.android.norbyvoicelibrary I/com.amazon.identity.auth.device.appid.APIKeyDecoder: Begin decoding API Key for packageName=com.willblaschko.android.norbyvoicelibrary
07-03 00:08:09.595 27617-27617/com.willblaschko.android.norbyvoicelibrary D/com.amazon.identity.auth.device.appid.APIKeyDecoder.PII: APIKey:<obscured>
07-03 00:08:09.595 27617-27617/com.willblaschko.android.norbyvoicelibrary I/com.amazon.identity.auth.device.appid.APIKeyDecoder: verifyPayload for packageName=com.willblaschko.android.norbyvoicelibrary
07-03 00:08:09.595 27617-27617/com.willblaschko.android.norbyvoicelibrary D/com.amazon.identity.auth.device.appid.APIKeyDecoder.PII: Validating MD5 signature in API key:<obscured>
07-03 00:08:09.597 27617-27617/com.willblaschko.android.norbyvoicelibrary I/com.amazon.identity.auth.device.utils.PackageSignatureUtil: num sigs = 1
07-03 00:08:09.598 27617-27617/com.willblaschko.android.norbyvoicelibrary D/com.amazon.identity.auth.device.utils.PackageSignatureUtil.PII: Fingerprint checking:<obscured>
07-03 00:08:09.598 27617-27617/com.willblaschko.android.norbyvoicelibrary I/com.amazon.identity.auth.device.appid.APIKeyDecoder: Number of signatures = 1
07-03 00:08:09.598 27617-27617/com.willblaschko.android.norbyvoicelibrary D/com.amazon.identity.auth.device.appid.APIKeyDecoder.PII: Fingerprint checking:<obscured>
07-03 00:08:09.598 27617-27617/com.willblaschko.android.norbyvoicelibrary W/com.amazon.identity.auth.device.appid.APIKeyDecoder: Failed to decode: Decoding failed: certificate fingerprint can't be verified! pkg=com.willblaschko.android.norbyvoicelibrary
07-03 00:08:09.598 27617-27617/com.willblaschko.android.norbyvoicelibrary W/com.amazon.identity.auth.device.appid.APIKeyDecoder: Unable to decode APIKey for pkg=com.willblaschko.android.norbyvoicelibrary
07-03 00:08:09.599 27617-27617/com.willblaschko.android.norbyvoicelibrary E/AuthorizationHandler: Unable to Use Amazon Authorization Manager. APIKey is incorrect or does not exist. Does assets/api_key.txt exist in the main application?
                                                                                                  java.lang.IllegalArgumentException: Invalid API Key
                                                                                                      at com.amazon.identity.auth.device.authorization.api.AmazonAuthorizationManager.<init>(AmazonAuthorizationManager.java:119)
                                                                                                      at com.willblaschko.android.alexa.AuthorizationManager.<init>(AuthorizationManager.java:56)
                                                                                                      at com.willblaschko.android.alexa.AlexaManager.<init>(AlexaManager.java:70)
                                                                                                      at com.willblaschko.android.alexa.AlexaManager.getInstance(AlexaManager.java:106)
                                                                                                      at com.willblaschko.android.norbyvoicelibrary.BaseActivity.initAlexaAndroid(BaseActivity.java:102)
                                                                                                      at com.willblaschko.android.norbyvoicelibrary.BaseActivity.onCreate(BaseActivity.java:69)
                                                                                                      at com.willblaschko.android.norbyvoicelibrary.MainActivity.onCreate(MainActivity.java:31)
                                                                                                      at android.app.Activity.performCreate(Activity.java:5990)
                                                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
                                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                                                                      at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                      at android.os.Looper.loop(Looper.java:135)
                                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
07-03 00:08:09.747 2562-2626/com.google.android.gms I/Icing: Indexing 8C6ADAA866694496E0FD43782A767CE3527B56CD from com.google.android.gms

**Comment by amiga** [comment]
I did not realise you should sign the apk each time and run that one, it has finally begun to work now (I had removed signing stuff from the gradle file). Well I dont get any errors, strange thing is I log into amazon then it directs me to a weird error page you can see here https://dl.dropboxusercontent.com/u/4194619/Snap%202017-07-03%20at%2000.32.10.png

**Comment by amiga** [comment]
OK Apologies I had wrong package name in manifest where it says  . Its working.
