### ISSUE TITLE
Log in issue

### ISSUE THREAD

**Issue by rohith-krish** [willblaschko/AlexaAndroid#107]
While trying to log in the Alexa Amazon account for authenticating, it is always showing error.

**Comment by ihavenoface5** [comment]
A couple of things to check:

1. Your api_key.txt is in your src/assets folder.
2. Your PRODUCT_ID matches the one set up on AVS

Check your Android log. Usually when a login fails there is some useful information there.

**Comment by Gmrevo** [comment]
@rohith-krish @ihavenoface5 Hi Guys,
I have made all necessary changes but I am facing this error:
04-27 16:19:15.742 28483-28483/? E/AuthorizationHandler: **Unable to Use Amazon Authorization Manager. APIKey is incorrect or does not exist. Does assets/api_key.txt exist in the main application?**
    java.lang.IllegalArgumentException: Invalid API Key
        at com.amazon.identity.auth.device.authorization.api.AmazonAuthorizationManager.<init>(AmazonAuthorizationManager.java:119)
        at com.willblaschko.android.alexa.AuthorizationManager.<init>(AuthorizationManager.java:56)
        at com.willblaschko.android.alexa.AlexaManager.<init>(AlexaManager.java:70)
        at com.willblaschko.android.alexa.AlexaManager.getInstance(AlexaManager.java:106)
        at com.willblaschko.android.alexavoicelibraryrobosys.BaseActivity.initAlexaAndroid(BaseActivity.java:101)
        at com.willblaschko.android.alexavoicelibraryrobosys.BaseActivity.onCreate(BaseActivity.java:68)
        at com.willblaschko.android.alexavoicelibraryrobosys.MainActivity.onCreate(MainActivity.java:30)
        at android.app.Activity.performCreate(Activity.java:6672)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2612)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
![screenshot from 2018-04-27 16-39-14](https://user-images.githubusercontent.com/11976260/39359913-9f4b3874-4a39-11e8-85ff-45d782e27eed.png)

**Comment by Prakhar-Agarwal-byte** [comment]
You can only use library with android O or below because it uses lower version of Login with Amazon SDK.
