### ISSUE TITLE
 java.lang.IllegalArgumentException: Invalid API Key

### ISSUE THREAD

**Issue by abhijagtap73** [willblaschko/AlexaAndroid#63]
Hi, I have a problem with signed apk, my alexa application code working fine on emulator but while i generated apk(use gradle assembleRelease) and install on device then gives 

`E/AuthorizationHandler: Unable to Use Amazon Authorization Manager. APIKey is incorrect or does not exist. Does assets/api_key.txt exist in the main application?
                                                         java.lang.IllegalArgumentException: Invalid API Key
                                                             at com.amazon.identity.auth.device.authorization.api.AmazonAuthorizationManager.<init>(AmazonAuthorizationManager.java:119)
                                                             at com.willblaschko.android.alexa.AuthorizationManager.<init>(AuthorizationManager.java:56)
                                                             at com.willblaschko.android.alexa.AlexaManager.<init>(AlexaManager.java:62)
                                                             at com.willblaschko.android.alexa.AlexaManager.getInstance(AlexaManager.java:86)`

please suggest me where i am wrong, checked twice api_key.txt file in asset and compared with alexa (security profile->android/kindle setting).

**Comment by amitks2015** [comment]
Usually it happens when debug build gets installed on the device. Make sure
you are installing release build only.

Thanks,
Amit

**Comment by abhijagtap73** [comment]
Actually i observed, my `SigningKey.getCertificateMD5Fingerprint(this)` gives different Signature and gradlew assembleRelease gives different Signature, hence need me to register both packages in to into device and for testing on emulator need to use different api_key and for release different. why i am getting two Signature?
