### ISSUE TITLE
okhttp3.internal.framed.StreamResetException: stream was reset: CANCEL

### ISSUE THREAD

**Issue by KushtrimPacaj** [willblaschko/AlexaAndroid#96]
Hi, I've been getting this error on my requests to Alexa AVS a lot. I am aware that this most probably isn't a bug for *this* library, it's either okhttp or Amazon Avs server's, but I would like to know whether anyone was able to find a workaound/solution for this problem.

```
okhttp3.internal.framed.StreamResetException: stream was reset: CANCEL
06-13 14:30:29.890 3419-3531/com.kushtrim.myapp W/System.err:     at okhttp3.internal.framed.FramedStream$FramedDataSource.checkNotClosed(FramedStream.java:441)
06-13 14:30:29.890 3419-3531/com.kushtrim.myapp W/System.err:     at okhttp3.internal.framed.FramedStream$FramedDataSource.read(FramedStream.java:343)
06-13 14:30:29.890 3419-3531/com.kushtrim.myapp W/System.err:     at okio.ForwardingSource.read(ForwardingSource.java:35)
06-13 14:30:29.890 3419-3531/com.kushtrim.myapp W/System.err:     at okio.RealBufferedSource$1.read(RealBufferedSource.java:409)
06-13 14:30:29.890 3419-3531/com.kushtrim.myapp W/System.err:     at java.io.InputStream.read(InputStream.java:162)
06-13 14:30:29.890 3419-3531/com.kushtrim.myapp W/System.err:     at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2146)
06-13 14:30:29.890 3419-3531/com.kushtrim.myapp W/System.err:     at org.apache.commons.io.IOUtils.copy(IOUtils.java:2102)
06-13 14:30:29.890 3419-3531/com.kushtrim.myapp W/System.err:     at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2123)
06-13 14:30:29.890 3419-3531/com.kushtrim.myapp W/System.err:     at org.apache.commons.io.IOUtils.copy(IOUtils.java:2078)
06-13 14:30:29.890 3419-3531/com.kushtrim.myapp W/System.err:     at org.apache.commons.io.IOUtils.toByteArray(IOUtils.java:721)
06-13 14:30:29.890 3419-3531/com.kushtrim.myapp W/System.err:     at com.willblaschko.android.alexa.interfaces.response.ResponseParser.parseResponse(ResponseParser.java:84)
06-13 14:30:29.890 3419-3531/com.kushtrim.myapp W/System.err:     at com.willblaschko.android.alexa.interfaces.response.ResponseParser.parseResponse(ResponseParser.java:73)
06-13 14:30:29.890 3419-3531/com.kushtrim.myapp W/System.err:     at com.willblaschko.android.alexa.interfaces.SendEvent.parseResponse(SendEvent.java:105)
06-13 14:30:29.890 3419-3531/com.kushtrim.myapp W/System.err:     at com.willblaschko.android.alexa.interfaces.SendEvent.completePost(SendEvent.java:76)
06-13 14:30:29.890 3419-3531/com.kushtrim.myapp W/System.err:     at com.willblaschko.android.alexa.interfaces.speechrecognizer.SpeechSendAudio.sendAudio(SpeechSendAudio.java:51)
06-13 14:30:29.890 3419-3531/com.kushtrim.myapp W/System.err:     at com.willblaschko.android.alexa.AlexaManager$4$1$1.doInBackground(AlexaManager.java:157)
06-13 14:30:29.890 3419-3531/com.kushtrim.myapp W/System.err:     at com.willblaschko.android.alexa.AlexaManager$4$1$1.doInBackground(AlexaManager.java:153)
06-13 14:30:29.890 3419-3531/com.kushtrim.myapp W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:292)
06-13 14:30:29.890 3419-3531/com.kushtrim.myapp W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-13 14:30:29.890 3419-3531/com.kushtrim.myapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
06-13 14:30:29.890 3419-3531/com.kushtrim.myapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
06-13 14:30:29.890 3419-3531/com.kushtrim.myapp W/System.err:     at java.lang.Thread.run(Thread.java:818)
06-13 14:30:29.890 3419-3531/com.kushtrim.myapp E/Alexa_ResponseParser: Error copying bytes[]
```

**Comment by MegatronKing** [comment]
I have the same problem when used okhttp to connect with AVS server.
